name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-test-deploy: # this is the job name
    runs-on: ubuntu-latest # this is the runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Start Containers
        run: docker compose up -d --build

      - name: Wait for Services
        run: sleep 10

      - name: Test Backend
        run: curl http://localhost:5000

      - name: Stop Containers
        run: docker compose down